apiVersion: v1
kind: Service
metadata:
  name: buoy
  labels:
    app.kubernetes.io/name: buoy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: buoy
  ports:
    - name: http
      port: 8090
      targetPort: http
